// Choose a cache name
const cacheName = 'cache-v1'

// List the files to precache
const precacheResources = [
  './',
  './index.html',
  './main.css',
  './manifest.json',
  './assets/logo/128.png',
  './assets/logo/192.png',
  './assets/logo/256.png',
  './assets/logo/384.png',
  './assets/logo/512.png',
  './audios/glitch_radio.mp3',
  './audios/musica.mp3',
  './audios/pora_abrindo.mp3',
  './audios/porta_efeito.mp3',
  './audios/sound_button.mp3',
  '.imagens/32.png',
  '.imagens/64.png',
  '.imagens/a_verde.png',
  '.imagens/abre_gaveta.png',
  '.imagens/alfabeto_menor_64.png',
  '.imagens/alfabeto_mini_24_30.png',
  '.imagens/afabeto_spritesheet.png',
  '.imagens/arbusto_flor9.png',
  '.imagens/arbusto_flor95.png',
  '.imagens/arbusto83.png',
  '.imagens/boneco_entidade.png',
  '.imagens/boneco_entidade0.png',
  '.imagens/boneco_homem_inv.png',
  '.imagens/boneco_homem_p.png',
  '.imagens/boneco_homem.png',
  '.imagens/boneco_mulher_inv.png',
  '.imagens/boneco_mulher_p.png',
  '.imagens/boneco_mulher.png',
  '.imagens/botao_cofre.png',
  '.imagens/botao_login.png',
  '.imagens/botao_start.png',
  '.imagens/cofre_aberto.png',
  '.imagens/cofre.png',
  '.imagens/cofre1.png',
  '.imagens/enigma_final_tela_cheia.png',
  '.imagens/enigma_final.png',
  '.imagens/entidade52.png',
  '.imagens/escrivaninha.png',
  '.imagens/estante_livros.png',
  '.imagens/estante_m3.png',
  '.imagens/estante.png',
  '.imagens/estante2.png',
  '.imagens/gaveta4_a.png',
  '.imagens/gaveta4_f.png',
  '.imagens/i_verde.png',
  '.imagens/icone_login.png',
  '.imagens/imagem_eng5_ss.png',
  '.imagens/inventario.png',
  '.imagens/janela.png',
  '.imagens/letra_a_enigma_final.png',
  '.imagens/mesa_m1.png',
  '.imagens/numeros_ss.png',
  '.imagens/painel_1989.png',
  '.imagens/papel_bandeiras.png',
  '.imagens/papel_enrolado.png',
  '.imagens/papel_enroladog.png',
  '.imagens/parede_mia.png',
  '.imagens/parede_mia1.png',
  '.imagens/parede_rasgada.png',
  '.imagens/parede_rasgadab.png',
  '.imagens/parede_sebas.png',
  '.imagens/porta_final_aberta.png',
  '.imagens/porta_final.png',
  '.imagens/porta_final1.png',
  '.imagens/porta_verde_c.png',
  '.imagens/porta_verde.png',
  '.imagens/provisorio.png',
  '.imagens/room_riddle_1.png',
  '.imagens/room_riddle_2.png',
  '.imagens/room_riddle.png',
  '.imagens/seleciona.png',
  '.imagens/seta_direita_a.png',
  '.imagens/seta_direita_teste.png',
  '.imagens/seta_direita.png',
  '.imagens/seta_down_enigma_fina.png',
  '.imagens/seta_down_enigma_final.png',
  '.imagens/seta_down.png',
  '.imagens/seta_esq.png',
  '.imagens/seta_esquerd.png',
  '.imagens/seta_esquerda.png',
  '.imagens/setajump.png',
  '.imagens/suporte_bonecos.png',
  '.imagens/tela_1989.png',
  '.imagens/tela_cofre.png',
  '.imagens/tela_eng5_1.png',
  '.imagens/tela_eng5_2.png',
  '.imagens/tela_inicio_1.png',
  '.imagens/tela_inicio.png',
  '.imagens/tela_papel.png',
  '.imagens/tela_recompensa.png',
  '.imagens/tela_sala_a.png',
  '.imagens/tela_sala_b.png',
  '.imagens/tela_sala_c.png',
  '.imagens/tela_sala.png',
  '.imagens/tela-cheia_a.png',
  '.imagens/tela-cheia_b.png',
  '.imagens/tela-cheia_c.png',
  '.imagens/tela-cheia_d.png',
  '.imagens/tela-cheia_e.png',
  '.imagens/tela-cheia_f.png',
  '.imagens/tela-cheia.png',
  '.imagens/teste_inv.png',
  '.imagens/teste_inv2.png',
  '.imagens/topo_estante.png',
  '.imagens/v_verde.png',
  '.imagens/vaso_c_girassol.png',
  '.imagens/vaso1.png',
  '.imagens/walkie_talkie.png',
  '.imagens/you_win.png',
  '.js/abertura_jogo.js',
  '.js/axios_min.js',
  '.js/cofre_aberto.js',
  '.js/config.js',
  '.js/enigma_final_mia.js',
  '.js/enigma_final_sebastian.js',
  '.js/index.js',
  '.js/phaser.min.js',
  '.js/sala_m1.js',
  '.js/sala_m2.js',
  '.js/sala_m3.js',
  '.js/sala_m4.js',
  '.js/sala_s1.js',
  '.js/sala_s2.js',
  '.js/sala_s3.js',
  '.js/sala_s4.js',
  '.js/tela_cofre.js',
  '.js/tela_eng2.js',
  '.js/tela_eng5.js',
  '.js/tela_eng6.js',
  '.js/tela_final.js',
  '.js/tela_gaveta.js',
  '.js/tela_papel.js',
  '.js/tela_papel5.js',
  '.js/tela_recompensa.js',
  '.js/ela_sala.js'
]

// When the service worker is installing, open the cache and add the precache resources to it
self.addEventListener('install', (event) => {
  console.log('Service worker install event!')
  event.waitUntil(caches.open(cacheName).then((cache) => cache.addAll(precacheResources)))
})

self.addEventListener('activate', (event) => {
  console.log('Service worker activate event!')
})

// When there's an incoming fetch request, try and respond with a precached resource, otherwise fall back to the network
self.addEventListener('fetch', function (event) {
  event.respondWith(
    caches.match(event.request).then(function (response) {
      return response || fetch(event.request)
    })
  )
})
